general {
    hide_cursor = true
}

background {
    monitor = 
    path = /home/testuser/Pictures/Wallpaper/10. Abyssal Wave.png
    blur_passes = 1
    blur_size = 5
}

input-field {
    monitor = 
    size = 300, 50
    position = 0, -80
    font_family = JetBrainsMono Nerd Font
    font_size = 18
    outline_thickness = 2
    dots_size = 0.2
    fade_on_empty = false
}

label {
    monitor = 
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 48
    position = 0, 80
}
