splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/testuser/Pictures/Wallpaper/10. Abyssal Wave.png  
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/testuser/Pictures/Wallpaper/purple-girl.png
    fit_mode = cover
}

