# FONT

font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 12.0
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E62F,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F31C,U+F400-U+F4A9,U+F500-U+F8FF Symbols Nerd Font
# CURSOR

cursor_shape beam
cursor_blink_interval 0.5

# WINDOW

background_opacity 0.82

confirm_os_window_close 0

window_padding_width 10

hide_window_decorations yes

# SCROLLBACK

scrollback_lines 10000

# PERFORMANCE

repaint_delay 10
input_delay 3
sync_to_monitor yes

# COLORS

foreground              #cdd6f4
background              #11111b

selection_foreground    #11111b
selection_background    #cba6f7

cursor                  #cba6f7
cursor_text_color       #11111b

url_color               #89b4fa

active_border_color     #cba6f7
inactive_border_color   #585b70

# BLACK

color0  #45475a
color8  #585b70

# RED

color1  #f38ba8
color9  #f38ba8

# GREEN

color2  #a6e3a1
color10 #a6e3a1

# YELLOW

color3  #f9e2af
color11 #f9e2af

# BLUE

color4  #89b4fa
color12 #89b4fa

# MAGENTA

color5  #cba6f7
color13 #cba6f7

# CYAN

color6  #94e2d5
color14 #94e2d5

# WHITE

color7  #bac2de
color15 #a6adc8

# TABS

tab_bar_style hidden

# BELL

enable_audio_bell no
visual_bell_duration 0

# MOUSE

copy_on_select yes

# Wichtig damit man Inhalte der Zwischenablage einfügen kann, die z.B. automatisch in Firefox etc kopiert wurden:

mouse_map middle click ungrabbed paste_from_clipboard
